package app.freerouting.io.specctra.parser

import java.io.IOException

/**
 * Interface for scanner generated by jflex.
 */
interface IJFlexScanner {

    /* Returns the current scope identifier. */
    fun get_scope_identifier(): String?

    /* Sets the current scope identifier. */
    fun set_scope_identifier(identifier: String?)

    /**
     * Reads the next token from the input file.
     */
    @Throws(IOException::class)
    fun next_token(): Any?

    /**
     * Reads the next token as a string from the input file.
     */
    fun next_string(): String?

    fun next_string(ignoreNewline: Boolean): String?

    fun next_string_list(): Array<String>?

    fun next_string_list(separator: Char): Array<String>?

    /**
     * Reads the next token as a double from the input file.
     */
    fun next_double(): Double?

    fun next_closing_bracket(): Boolean?

    /**
     * Starts a new state.
     */
    fun yybegin(p_new_state: Int)
}
